/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BookEditCard: typeof import('./src/components/BookEditCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NAnchor: typeof import('naive-ui')['NAnchor']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCardContent: typeof import('naive-ui')['NCardContent']
    NCardHeader: typeof import('naive-ui')['NCardHeader']
    NCardHeaderExtra: typeof import('naive-ui')['NCardHeaderExtra']
    NCardMeta: typeof import('naive-ui')['NCardMeta']
    NCardSubtitle: typeof import('naive-ui')['NCardSubtitle']
    NCardTitle: typeof import('naive-ui')['NCardTitle']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDi: typeof import('naive-ui')['NDi']
    NDivider: typeof import('naive-ui')['NDivider']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNDynamicTags: typeof import('naive-ui')['NNDynamicTags']
    NQr: typeof import('naive-ui')['NQr']
    NQrCode: typeof import('naive-ui')['NQrCode']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSeparator: typeof import('naive-ui')['NSeparator']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
  }
}
